
\newcommand{\refl}{\ensuremath{\text{refl}}}
\newcommand{\ext}{\ensuremath{\text{ext}}}

\newcommand{\id}{\ensuremath{\text{id}}}

\newcommand{\fst}{\ensuremath{\text{fst}}}
\newcommand{\snd}{\ensuremath{\text{snd}}}

\newcommand{\inl}{\ensuremath{\text{inl}}}
\newcommand{\inr}{\ensuremath{\text{inr}}}

\newcommand{\zero}{\ensuremath{\mathbf{0}}}
\newcommand{\one}{\ensuremath{\mathbf{1}}}

\newcommand{\oneelt}{\ensuremath{\star}}

\newtheorem{theorem}{Theorem}
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}

\theoremstyle{definition}
\newtheorem{example}[theorem]{Example}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{remark}[theorem]{Remark}
\newtheorem{note}[theorem]{Note}
\newtheorem{problem}{Problem}
\newtheorem{question}{Question}
\newtheorem*{principle}{Principle}

\newcommand{\sem}[1]{\ensuremath{\llbracket #1 \rrbracket}}

\newcommand{\elim}{\ensuremath{\text{elim}}}
\newcommand{\dmap}{\ensuremath{\text{dmap}}}

\newcommand{\fold}{\ensuremath{\text{fold}}}
\newcommand{\inn}{\ensuremath{\text{in}}}

\newcommand{\Bialg}{\ensuremath{\text{BiAlg}}}
\newcommand{\ALG}{\ensuremath{\overline{\text{Alg}}}}

%CwF
\newcommand{\Ty}{\ensuremath{\text{Ty}}}
\newcommand{\Tm}{\ensuremath{\text{Tm}}}
\newcommand{\p}[1]{\ensuremath{\textbf{p}(#1)}}
\newcommand{\ps}{\ensuremath{\textbf{p}}}
\newcommand{\vv}[1]{\ensuremath{\textbf{v}_{#1}}}

% For convenience
\newcommand{\muF}{\ensuremath{\mu F}}
\newcommand{\C}{\ensuremath{\mathbb{C}}}
\newcommand{\D}{\ensuremath{\mathbb{D}}}

\newcommand{\Set}{\ensuremath{\text{Set}}}
\newcommand{\Type}{\ensuremath{\text{Type}}}
\newcommand{\Fam}{\ensuremath{\text{Fam}}}
\newcommand{\semFam}{\ensuremath{\sem{\Fam}}}
\newcommand{\Pow}{\ensuremath{\text{Pow}}}

\newcommand{\invIm}[1]{\ensuremath{#1^{*}}}
