\newcommand{\Set}{\ensuremath{\text{Set}}}
\newcommand{\Fam}{\ensuremath{\text{Fam}}}

\newcommand{\refl}{\ensuremath{\text{refl}}}
\newcommand{\ext}{\ensuremath{\text{ext}}}

\newcommand{\id}{\ensuremath{\text{id}}}

\newtheorem{theorem}{Theorem}
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}

\theoremstyle{definition}
\newtheorem{example}[theorem]{Example}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{problem}{Problem}
\newtheorem*{principle}{Principle}

\newcommand{\sem}[1]{\ensuremath{\llbracket #1 \rrbracket}}

\newcommand{\elim}{\ensuremath{\text{elim}}}
\newcommand{\dmap}{\ensuremath{\text{dmap}}}

\newcommand{\fold}{\ensuremath{\text{fold}}}
\newcommand{\inn}{\ensuremath{\text{in}}}


% For convenience
\newcommand{\muF}{\ensuremath{\mu F}}
